apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email for Let's Encrypt notifications (certificate expiry, etc.)
    # Replace with your actual email
    email: yumethsumathipala@example.com
    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Optional: Staging issuer for testing (doesn't count against rate limits)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: yumethsumathipala@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
